"""Database module providing SQLAlchemy models and session management."""

from core.db.connection import engine, SessionLocal, get_session, get_db, get_engine
from core.db.models import (
    Base,
    Match,
    Odds,
    OddsSnapshot,
    Result,
    MARKET_SCHEMAS,
    MARKET_MODELS,
    FifaGoalsOUFeature,
    FifaGoalsOUModelScore,
    FifaGoalsOUTipLog,
    FifaAsianHandicapFeature,
    FifaAsianHandicapModelScore,
    FifaAsianHandicapTipLog,
    FifaMoneyLineFeature,
    FifaMoneyLineModelScore,
    FifaMoneyLineTipLog,
    EbasketOUFeature,
    EbasketOUModelScore,
    EbasketOUTipLog,
    EbasketMoneyLineFeature,
    EbasketMoneyLineModelScore,
    EbasketMoneyLineTipLog,
)

__all__ = [
    "engine",
    "SessionLocal",
    "get_session",
    "get_db",
    "get_engine",
    "Base",
    "Match",
    "Odds",
    "OddsSnapshot",
    "Result",
    "MARKET_SCHEMAS",
    "MARKET_MODELS",
    "FifaGoalsOUFeature",
    "FifaGoalsOUModelScore",
    "FifaGoalsOUTipLog",
    "FifaAsianHandicapFeature",
    "FifaAsianHandicapModelScore",
    "FifaAsianHandicapTipLog",
    "FifaMoneyLineFeature",
    "FifaMoneyLineModelScore",
    "FifaMoneyLineTipLog",
    "EbasketOUFeature",
    "EbasketOUModelScore",
    "EbasketOUTipLog",
    "EbasketMoneyLineFeature",
    "EbasketMoneyLineModelScore",
    "EbasketMoneyLineTipLog",
]
